/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacontrole;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author jaime
 */
public class FuncoesWindow extends javax.swing.JFrame {
    public boolean theresError;
    public String erro = "";
    /**
     * Creates new form FuncoesWindow
     */
    public FuncoesWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoFuncao = new javax.swing.ButtonGroup();
        tipoMalha = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FuncaoQuadrada = new javax.swing.JRadioButton();
        FuncaoDenteSerra = new javax.swing.JRadioButton();
        FuncaoDegrau = new javax.swing.JRadioButton();
        FuncaoAleatoria = new javax.swing.JRadioButton();
        FuncaoSenoidal = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PeriodoMinimo = new javax.swing.JTextField();
        PeriodoMaximo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        AmplitudeMinima = new javax.swing.JTextField();
        AmplitudeMaxima = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Amplitude = new javax.swing.JTextField();
        Offset = new javax.swing.JTextField();
        Periodo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        BotaoGerarFuncao = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        CheckMalhaFechada = new javax.swing.JRadioButton();
        CheckMalhaAberta = new javax.swing.JRadioButton();
        tipoControleComboBox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        parametrosPIDPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        kpTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        kiTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        kdTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tiTextField = new javax.swing.JTextField();
        tdTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        antiWindUpCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Tipo de Sinal");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TipoFuncao.add(FuncaoQuadrada);
        FuncaoQuadrada.setText("Quadrada");
        FuncaoQuadrada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FuncaoQuadradaStateChanged(evt);
            }
        });

        TipoFuncao.add(FuncaoDenteSerra);
        FuncaoDenteSerra.setText("Dente de Serra");
        FuncaoDenteSerra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FuncaoDenteSerraStateChanged(evt);
            }
        });

        TipoFuncao.add(FuncaoDegrau);
        FuncaoDegrau.setText("Degrau");
        FuncaoDegrau.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FuncaoDegrauStateChanged(evt);
            }
        });

        TipoFuncao.add(FuncaoAleatoria);
        FuncaoAleatoria.setText("Aleatória");
        FuncaoAleatoria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FuncaoAleatoriaStateChanged(evt);
            }
        });

        TipoFuncao.add(FuncaoSenoidal);
        FuncaoSenoidal.setSelected(true);
        FuncaoSenoidal.setText("Senoidal");
        FuncaoSenoidal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FuncaoSenoidalStateChanged(evt);
            }
        });
        FuncaoSenoidal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncaoSenoidalActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/seno.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/quedrada.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/degrau.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/aleatorio.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/denteSerra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FuncaoQuadrada)
                            .addComponent(FuncaoSenoidal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FuncaoDenteSerra))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FuncaoAleatoria)
                            .addComponent(FuncaoDegrau))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(FuncaoSenoidal)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(FuncaoQuadrada)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(FuncaoDenteSerra)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(FuncaoDegrau)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(FuncaoAleatoria)
                        .addGap(37, 37, 37))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setText("Período (s)");

        jLabel14.setText("Mínimo");

        jLabel15.setText("Máximo");

        PeriodoMinimo.setText("0");

        PeriodoMaximo.setText("10");
        PeriodoMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeriodoMaximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PeriodoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(PeriodoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(48, 48, 48))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PeriodoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("Amplitude (V)");

        AmplitudeMinima.setText("-4");

        AmplitudeMaxima.setText("4");
        AmplitudeMaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmplitudeMaximaActionPerformed(evt);
            }
        });

        jLabel12.setText("Mínima");

        jLabel13.setText("Máxima");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(AmplitudeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AmplitudeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmplitudeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmplitudeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(173, 122));

        jLabel7.setText("Amplitude:");

        jLabel8.setText("Offset:");

        jLabel9.setText("Período:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Amplitude)
                    .addComponent(Offset)
                    .addComponent(Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amplitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Offset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel16.setText("Parâmetros");

        BotaoGerarFuncao.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        BotaoGerarFuncao.setText("Gerar");
        BotaoGerarFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGerarFuncaoActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tipoMalha.add(CheckMalhaFechada);
        CheckMalhaFechada.setText("Malha Fechada");
        CheckMalhaFechada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckMalhaFechadaStateChanged(evt);
            }
        });

        tipoMalha.add(CheckMalhaAberta);
        CheckMalhaAberta.setSelected(true);
        CheckMalhaAberta.setText("Malha Aberta");
        CheckMalhaAberta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckMalhaAbertaStateChanged(evt);
            }
        });

        tipoControleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "PI", "PD", "PID", "PI-D" }));
        tipoControleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoControleComboBoxActionPerformed(evt);
            }
        });

        jLabel22.setText("Tipo de Controle");

        this.tipoControleComboBox.setVisible(false);
        this.jLabel22.setVisible(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckMalhaAberta)
                    .addComponent(CheckMalhaFechada)
                    .addComponent(jLabel22)
                    .addComponent(tipoControleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckMalhaAberta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckMalhaFechada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoControleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel17.setText("Malha");

        parametrosPIDPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setText("Kp");

        kpTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kpTextFieldKeyTyped(evt);
            }
        });

        jLabel19.setText("Ki");

        kiTextField.setEditable(false);
        kiTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kiTextFieldKeyTyped(evt);
            }
        });

        jLabel20.setText("Kd");

        kdTextField.setEditable(false);
        kdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdTextFieldActionPerformed(evt);
            }
        });
        kdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kdTextFieldKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel21.setText("Parâmetros PID");

        jLabel24.setText("Ti");

        jLabel25.setText("Td");

        tiTextField.setEditable(false);
        tiTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiTextFieldKeyTyped(evt);
            }
        });

        tdTextField.setEditable(false);
        tdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tdTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout parametrosPIDPanelLayout = new javax.swing.GroupLayout(parametrosPIDPanel);
        parametrosPIDPanel.setLayout(parametrosPIDPanelLayout);
        parametrosPIDPanelLayout.setHorizontalGroup(
            parametrosPIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parametrosPIDPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(46, 46, 46))
            .addGroup(parametrosPIDPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(parametrosPIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(25, 25, 25)
                .addGroup(parametrosPIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(kiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiTextField)
                    .addComponent(tdTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        parametrosPIDPanelLayout.setVerticalGroup(
            parametrosPIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametrosPIDPanelLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(5, 5, 5)
                .addGroup(parametrosPIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(kpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametrosPIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(kiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametrosPIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(kdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametrosPIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametrosPIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel23.setText("Filtros");

        antiWindUpCheckBox.setText("Anti Windup");
        antiWindUpCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antiWindUpCheckBoxActionPerformed(evt);
            }
        });

        this.antiWindUpCheckBox.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel23))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(antiWindUpCheckBox)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(antiWindUpCheckBox)
                .addGap(0, 61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parametrosPIDPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(139, 139, 139)
                .addComponent(jLabel17)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoGerarFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(parametrosPIDPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24)
                .addComponent(BotaoGerarFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        this.jPanel2.setVisible(false);
        this.jPanel3.setVisible(false);
        this.parametrosPIDPanel.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FuncaoSenoidalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncaoSenoidalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FuncaoSenoidalActionPerformed

    private void AmplitudeMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmplitudeMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmplitudeMaximaActionPerformed

    private void PeriodoMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeriodoMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PeriodoMaximoActionPerformed

    private void BotaoGerarFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGerarFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoGerarFuncaoActionPerformed

    private void FuncaoSenoidalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FuncaoSenoidalStateChanged
        // TODO add your handling code here:
        if(this.FuncaoSenoidal.isSelected()){
            jPanel3.setVisible(false);
            jPanel2.setVisible(false);
            Amplitude.setEditable(true);
            Periodo.setEditable(true);
            Offset.setEditable(true);
        }
    }//GEN-LAST:event_FuncaoSenoidalStateChanged

    private void FuncaoQuadradaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FuncaoQuadradaStateChanged
        // TODO add your handling code here:
        if(this.FuncaoQuadrada.isSelected()){
            jPanel3.setVisible(false);
            jPanel2.setVisible(false);
            Amplitude.setEditable(true);
            Periodo.setEditable(true);
            Offset.setEditable(true);
        }
    }//GEN-LAST:event_FuncaoQuadradaStateChanged

    private void FuncaoDenteSerraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FuncaoDenteSerraStateChanged
        // TODO add your handling code here:
        if(this.FuncaoDenteSerra.isSelected()){
            jPanel3.setVisible(false);
            jPanel2.setVisible(false);
            Amplitude.setEditable(true);
            Periodo.setEditable(true);
            Offset.setEditable(true);
        }
    }//GEN-LAST:event_FuncaoDenteSerraStateChanged

    private void FuncaoDegrauStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FuncaoDegrauStateChanged
        // TODO add your handling code here:
        if(this.FuncaoDegrau.isSelected()){
            jPanel3.setVisible(false);
            jPanel2.setVisible(false);
            Amplitude.setEditable(true);
            Periodo.setEditable(false);
            Offset.setEditable(true);
        }
    }//GEN-LAST:event_FuncaoDegrauStateChanged

    private void FuncaoAleatoriaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FuncaoAleatoriaStateChanged
        // TODO add your handling code here:
        if(this.FuncaoAleatoria.isSelected()){
            jPanel3.setVisible(true);
            jPanel2.setVisible(true);
            Amplitude.setEditable(false);
            Periodo.setEditable(false);
            Offset.setEditable(true);
        }
    }//GEN-LAST:event_FuncaoAleatoriaStateChanged

    private void kdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdTextFieldActionPerformed

    private void CheckMalhaFechadaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckMalhaFechadaStateChanged
        // TODO add your handling code here:
        if(this.CheckMalhaFechada.isSelected()){
            this.parametrosPIDPanel.setVisible(true);
            this.jLabel22.setVisible(true);
            this.tipoControleComboBox.setVisible(true);
        }
    }//GEN-LAST:event_CheckMalhaFechadaStateChanged

    private void CheckMalhaAbertaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckMalhaAbertaStateChanged
        // TODO add your handling code here:
        if(this.CheckMalhaAberta.isSelected()){
            this.parametrosPIDPanel.setVisible(false);
            this.jLabel22.setVisible(false);
            this.tipoControleComboBox.setVisible(false);
        }
    }//GEN-LAST:event_CheckMalhaAbertaStateChanged

    public boolean isAntiWindUpActive(){
        return this.antiWindUpCheckBox.isSelected();
    }
    
    private void tipoControleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoControleComboBoxActionPerformed
        int tipoControle = this.tipoControleComboBox.getSelectedIndex();
        
        if(tipoControle == 0){//tipo P
            this.kpTextField.setEditable(true);
            this.kiTextField.setEditable(false);
            this.kdTextField.setEditable(false);
            
            this.tiTextField.setEditable(false);
            this.tdTextField.setEditable(false);
            this.antiWindUpCheckBox.setEnabled(false);
            this.antiWindUpCheckBox.setSelected(false);
        }
        else if(tipoControle == 1){//tipo PI
            this.kpTextField.setEditable(true);
            this.kiTextField.setEditable(true);
            this.kdTextField.setEditable(false);
            
            this.tiTextField.setEditable(true);
            this.tdTextField.setEditable(false);
            this.antiWindUpCheckBox.setEnabled(true);
        }
        else if(tipoControle == 2){//tipo PD
            this.kpTextField.setEditable(true);
            this.kiTextField.setEditable(false);
            this.kdTextField.setEditable(true);
            
            this.tiTextField.setEditable(false);
            this.tdTextField.setEditable(true);
            this.antiWindUpCheckBox.setEnabled(true);
        }
        else if(tipoControle == 3){//tipo PID
            this.kpTextField.setEditable(true);
            this.kiTextField.setEditable(true);
            this.kdTextField.setEditable(true);
            
            this.tiTextField.setEditable(true);
            this.tdTextField.setEditable(true);
            this.antiWindUpCheckBox.setEnabled(true);
        }
        else if(tipoControle == 4){//tipo PI-D
            this.kpTextField.setEditable(true);
            this.kiTextField.setEditable(true);
            this.kdTextField.setEditable(true);
            
            this.tiTextField.setEditable(true);
            this.tdTextField.setEditable(true);
            this.antiWindUpCheckBox.setEnabled(true);
        }
    }//GEN-LAST:event_tipoControleComboBoxActionPerformed

    private void kpTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kpTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_kpTextFieldKeyTyped

    private void kiTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kiTextFieldKeyTyped
        // TODO add your handling code here:
        this.tiTextField.setText("NaN");
    }//GEN-LAST:event_kiTextFieldKeyTyped

    private void kdTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kdTextFieldKeyTyped
        // TODO add your handling code here:
        this.tdTextField.setText("NaN");
    }//GEN-LAST:event_kdTextFieldKeyTyped

    private void tiTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiTextFieldKeyTyped
        // TODO add your handling code here:
        this.kiTextField.setText("NaN");
    }//GEN-LAST:event_tiTextFieldKeyTyped

    private void tdTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tdTextFieldKeyTyped
        // TODO add your handling code here:
        this.kdTextField.setText("NaN");
    }//GEN-LAST:event_tdTextFieldKeyTyped

    private void antiWindUpCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antiWindUpCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antiWindUpCheckBoxActionPerformed

    public String getKpValor(){
        return kpTextField.getText();
    }
    
    public String getKiValor(){
        return kiTextField.getText();
    }
    
    public String getKdValor(){
        return kdTextField.getText();
    }
    
    public String getTiValor(){
        return tiTextField.getText();
    }
    
    public String getTdValor(){
        return tdTextField.getText();
    }
    
    public int getSelectedControle(){
        return this.tipoControleComboBox.getSelectedIndex();
    }
    
    public String GetFuncaoSelecionada(){
        String funcao;
        if (FuncaoSenoidal.isSelected()) funcao = "senoidal";
        else if (FuncaoQuadrada.isSelected()) funcao = "quadrada";
        else if (FuncaoDegrau.isSelected()) funcao = "degrau";
        else if (FuncaoDenteSerra.isSelected()) funcao = "serra";
        else if (FuncaoAleatoria.isSelected()) funcao = "aleatoria";
        else funcao = "erro";
        return funcao;
    }
    public double GetAmplitude(){
        return Double.parseDouble(Amplitude.getText());
    }
    public double GetPeriodo(){
        return Double.parseDouble(Periodo.getText());
    }
    public double GetOffset(){
        double offset = 0;
        try{
            offset = Double.parseDouble(Offset.getText());
        } catch (Exception e ){
            if(this.isMalhaFechada()){
                theresError = true;
                erro += "Offset inválido\n";
            }
        }
        return offset;
    }
    public double GetAmplitudeMinima(){
        return Double.parseDouble(AmplitudeMinima.getText());
    }
    public double GetAmplitudeMaxima(){
        return Double.parseDouble(AmplitudeMaxima.getText());
    }
    public double GetPeridoMinimo(){
        return Double.parseDouble(PeriodoMinimo.getText());
    }
    public double GetPeriodoMaximo(){
        return Double.parseDouble(PeriodoMaximo.getText());
    }
    public boolean isMalhaFechada(){
        return CheckMalhaFechada.isSelected();
    }
    public void mostrarErro(){
        JOptionPane.showMessageDialog(null, this.erro, "Erro!", JOptionPane.ERROR_MESSAGE);
    } 
    public void addGerarFuncaoListener(ActionListener listen){
        BotaoGerarFuncao.addActionListener(listen);
    }
    
    public double[] getPIDValores(){
        theresError = false;
        double p = 0, i = 0, d = 0;
        
        double[] param = new double[3];
        try{
            p = Double.parseDouble(this.getKpValor());
        } catch (Exception e) {
            theresError = true;
            erro += "Valor de Kp inválido.\n";
        }
        
        if(this.getKiValor().isEmpty() && this.getTiValor().isEmpty()){
            i = 0;
        }
        else{
            if("NaN".equals(this.getKiValor())){
                try{
                    i = Double.parseDouble(this.getTiValor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Ti inválido.\n";
                }
            }
            else{
                try{
                    i = Double.parseDouble(this.getKiValor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Ki inválido.\n";
                }
            }
        }
        
        if(this.getKdValor().isEmpty() && this.getTdValor().isEmpty()){
            d = 0;
        }
        else{
            if("NaN".equals(this.getKdValor())){
                try{
                    d = Double.parseDouble(this.getTdValor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Td inválido.\n";
                }
            }
            else{
                try{
                    i = Double.parseDouble(this.getKdValor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Kd inválido.\n";
                }
            }
        }
        
        param[0] = p;
        param[1] = i;
        param[2] = d;
        
        return param;
    }
    
    public boolean isKi(){
        if(this.getKiValor().isEmpty() && this.getTiValor().isEmpty()){
            return false;
        }
        else{
            return !"NaN".equals(this.getKiValor());
        }
    }
    
    public boolean isKd(){
        if(this.getKdValor().isEmpty() && this.getTdValor().isEmpty()){
            return false;
        }
        else{
            return !"NaN".equals(this.getKdValor());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amplitude;
    private javax.swing.JTextField AmplitudeMaxima;
    private javax.swing.JTextField AmplitudeMinima;
    private javax.swing.JButton BotaoGerarFuncao;
    private javax.swing.JRadioButton CheckMalhaAberta;
    private javax.swing.JRadioButton CheckMalhaFechada;
    private javax.swing.JRadioButton FuncaoAleatoria;
    private javax.swing.JRadioButton FuncaoDegrau;
    private javax.swing.JRadioButton FuncaoDenteSerra;
    private javax.swing.JRadioButton FuncaoQuadrada;
    private javax.swing.JRadioButton FuncaoSenoidal;
    private javax.swing.JTextField Offset;
    private javax.swing.JTextField Periodo;
    private javax.swing.JTextField PeriodoMaximo;
    private javax.swing.JTextField PeriodoMinimo;
    private javax.swing.ButtonGroup TipoFuncao;
    private javax.swing.JCheckBox antiWindUpCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kdTextField;
    private javax.swing.JTextField kiTextField;
    private javax.swing.JTextField kpTextField;
    private javax.swing.JPanel parametrosPIDPanel;
    private javax.swing.JTextField tdTextField;
    private javax.swing.JTextField tiTextField;
    private javax.swing.JComboBox<String> tipoControleComboBox;
    private javax.swing.ButtonGroup tipoMalha;
    // End of variables declaration//GEN-END:variables
}
