/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacontrole;

import java.awt.event.ActionListener;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jaime
 */
public class MainWindow extends javax.swing.JFrame {
    ImageIcon iconON = new ImageIcon(SistemaControle.class.getResource("/imagens/diagrama_on.png"));
    ImageIcon iconOFF = new ImageIcon(SistemaControle.class.getResource("/imagens/diagrama_off.png"));
    ImageIcon iconRV = new ImageIcon(SistemaControle.class.getResource("/imagens/diagrama_reverse.png"));

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ControleSelecao = new javax.swing.ButtonGroup();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        PainelEntrada = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SaidaCanal0 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        SaidaCanal1 = new javax.swing.JCheckBox();
        SaidaCanal2 = new javax.swing.JCheckBox();
        SaidaCanal3 = new javax.swing.JCheckBox();
        SaidaCanal4 = new javax.swing.JCheckBox();
        SaidaCanal5 = new javax.swing.JCheckBox();
        SaidaCanal6 = new javax.swing.JCheckBox();
        BotaoLer = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ControleCanal0 = new javax.swing.JRadioButton();
        ControleCanal1 = new javax.swing.JRadioButton();
        PainelSaida = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BotaoTipoDeFuncao = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pararSinalBt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tanque1Progress = new javax.swing.JProgressBar();
        tanque2Progress = new javax.swing.JProgressBar();
        LabelDiagrama = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        logMenuItem = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 760));
        setResizable(false);

        PainelEntrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PainelEntradaLayout = new javax.swing.GroupLayout(PainelEntrada);
        PainelEntrada.setLayout(PainelEntradaLayout);
        PainelEntradaLayout.setHorizontalGroup(
            PainelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        PainelEntradaLayout.setVerticalGroup(
            PainelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SaidaCanal0.setSelected(true);
        SaidaCanal0.setText("Canal 0");
        SaidaCanal0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal0ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Variáveis de Saída");

        SaidaCanal1.setText("Canal 1");
        SaidaCanal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal1ActionPerformed(evt);
            }
        });

        SaidaCanal2.setText("Canal 2");
        SaidaCanal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal2ActionPerformed(evt);
            }
        });

        SaidaCanal3.setText("Canal 3");
        SaidaCanal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal3ActionPerformed(evt);
            }
        });

        SaidaCanal4.setText("Canal 4");
        SaidaCanal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal4ActionPerformed(evt);
            }
        });

        SaidaCanal5.setText("Canal 5");
        SaidaCanal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal5ActionPerformed(evt);
            }
        });

        SaidaCanal6.setText("Canal 6");
        SaidaCanal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal6ActionPerformed(evt);
            }
        });

        BotaoLer.setText("LER");
        BotaoLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SaidaCanal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaidaCanal5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SaidaCanal2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaidaCanal6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SaidaCanal3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoLer))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SaidaCanal0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaidaCanal4)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaidaCanal0)
                    .addComponent(SaidaCanal4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaidaCanal1)
                    .addComponent(SaidaCanal5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaidaCanal2)
                    .addComponent(SaidaCanal6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaidaCanal3)
                    .addComponent(BotaoLer))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Variáveis de Controle");

        ControleSelecao.add(ControleCanal0);
        ControleCanal0.setSelected(true);
        ControleCanal0.setText("Canal 0");
        ControleCanal0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControleCanal0ActionPerformed(evt);
            }
        });

        ControleSelecao.add(ControleCanal1);
        ControleCanal1.setText("Canal 1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ControleCanal1)
                            .addComponent(ControleCanal0))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControleCanal0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControleCanal1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelSaida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PainelSaidaLayout = new javax.swing.GroupLayout(PainelSaida);
        PainelSaida.setLayout(PainelSaidaLayout);
        PainelSaidaLayout.setHorizontalGroup(
            PainelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        PainelSaidaLayout.setVerticalGroup(
            PainelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jLabel7.setText("Níveis dos Tanques");

        jLabel8.setText("Tensão das bombas");

        BotaoTipoDeFuncao.setText("Tipo de Função");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        pararSinalBt.setBackground(new java.awt.Color(255, 255, 255));
        pararSinalBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/stop.png"))); // NOI18N
        pararSinalBt.setText("Parar Sinal");
        pararSinalBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararSinalBtActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tanque1Progress.setOrientation(1);
        tanque1Progress.setValue(50);
        tanque1Progress.setMaximumSize(new java.awt.Dimension(12, 10));
        tanque1Progress.setMinimumSize(new java.awt.Dimension(10, 10));
        tanque1Progress.setPreferredSize(new java.awt.Dimension(10, 10));
        tanque1Progress.setSize(new java.awt.Dimension(10, 10));

        tanque2Progress.setOrientation(1);
        tanque2Progress.setValue(50);

        LabelDiagrama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/diagrama_off.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/base.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("I");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelDiagrama, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tanque2Progress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanque1Progress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tanque1Progress, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(tanque2Progress, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelDiagrama))
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jMenu1.setText("Menu");

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        logMenuItem.setText("Log");
        logMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logMenuItemActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Abrir log sistema");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        logMenuItem.add(jMenuItem3);

        jMenuBar1.add(logMenuItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel8)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pararSinalBt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotaoTipoDeFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(PainelSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(pararSinalBt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotaoTipoDeFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void SaidaCanal0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal0ActionPerformed

    private void SaidaCanal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal1ActionPerformed

    private void SaidaCanal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal2ActionPerformed

    private void SaidaCanal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal3ActionPerformed

    private void SaidaCanal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal4ActionPerformed

    private void ControleCanal0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControleCanal0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ControleCanal0ActionPerformed

    private void SaidaCanal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal5ActionPerformed

    private void SaidaCanal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal6ActionPerformed

    private void BotaoLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLerActionPerformed

    private void logMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logMenuItemActionPerformed
        
    }//GEN-LAST:event_logMenuItemActionPerformed

    private void pararSinalBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararSinalBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pararSinalBtActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        
    }//GEN-LAST:event_jMenuItem3MouseClicked
    public void addLerListener(ActionListener e){
        this.BotaoLer.addActionListener(e);
    }
    
    public void addLogWindowOpenListener(ActionListener e){
        this.logMenuItem.addActionListener(e);
    }
    
    public void addPararSinalListener(ActionListener e){
        this.pararSinalBt.addActionListener(e);
    }
    
    public boolean isCanal0(){
        return SaidaCanal0.isSelected();
    }
    public boolean isCanal1(){
        return SaidaCanal1.isSelected();
    }
    public boolean isCanal2(){
        return SaidaCanal2.isSelected();
    }
    public boolean isCanal3(){
        return SaidaCanal3.isSelected();
    }
    public boolean isCanal4(){
        return SaidaCanal4.isSelected();
    }
    public boolean isCanal5(){
        return SaidaCanal5.isSelected();
    }
    public boolean isCanal6(){
        return SaidaCanal6.isSelected();
    }
    
    public boolean[] isCanalSelected(){
        boolean[] canaisSelecionados = new boolean[7];
        if(isCanal0())
            canaisSelecionados[0] = true;
        else 
            canaisSelecionados[0] = false;
        
        if(isCanal1())
            canaisSelecionados[1] = true;
        else 
            canaisSelecionados[1] = false;
        
        if(isCanal2())
            canaisSelecionados[2] = true;
        else 
            canaisSelecionados[2] = false;
        
        if(isCanal3())
            canaisSelecionados[3] = true;
        else 
            canaisSelecionados[3] = false;
        
        if(isCanal4())
            canaisSelecionados[4] = true;
        else 
            canaisSelecionados[4] = false;
        
        if(isCanal5())
            canaisSelecionados[5] = true;
        else 
            canaisSelecionados[5] = false;
        
        if(isCanal6())
            canaisSelecionados[6] = true;
        else 
            canaisSelecionados[6] = false;
        
        
        return canaisSelecionados;
    }
    
    public void updateCanal0(double _valor){
        String valor;
        valor = String.valueOf(_valor);
    }
    public void updateCanal1(double _valor){
        String valor;
        valor = String.valueOf(_valor);
    }
    public void mostrarErro(String erro){
        JOptionPane.showMessageDialog(null, erro, "Erro!", JOptionPane.ERROR_MESSAGE);
    }
    public void mostrarAviso(String erro){
        JOptionPane.showMessageDialog(null, erro, "Aviso!", JOptionPane.WARNING_MESSAGE);
    }
    public void addTipoFuncaoListener(ActionListener listen){
        BotaoTipoDeFuncao.addActionListener(listen);
    }
    
    public void setTanque1Progress(double prog){
        int n = (int) prog;
        this.tanque1Progress.setValue(n);
    }
//    public MainWindow(ImageIcon diagrama){
//        LabelDiagrama.setIcon(diagrama);
//    }
    public void setTanque2Progress(double prog){
        int n = (int) prog;
        this.tanque2Progress.setValue(n);
    }
    
    public void AtualizarDiagrama(String tipo){
        if(tipo.equals("ON")){
            this.LabelDiagrama.setIcon(iconON);
            this.LabelDiagrama.repaint();
        }
        else if(tipo.equals("OFF")){
            this.LabelDiagrama.setIcon(iconOFF);
            this.LabelDiagrama.repaint();
        }
        else if(tipo.equals("RV")){
            this.LabelDiagrama.setIcon(iconRV);
            this.LabelDiagrama.repaint();
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoLer;
    private javax.swing.JButton BotaoTipoDeFuncao;
    private javax.swing.JRadioButton ControleCanal0;
    private javax.swing.JRadioButton ControleCanal1;
    private javax.swing.ButtonGroup ControleSelecao;
    protected javax.swing.JLabel LabelDiagrama;
    protected javax.swing.JPanel PainelEntrada;
    protected javax.swing.JPanel PainelSaida;
    private javax.swing.JCheckBox SaidaCanal0;
    private javax.swing.JCheckBox SaidaCanal1;
    private javax.swing.JCheckBox SaidaCanal2;
    private javax.swing.JCheckBox SaidaCanal3;
    private javax.swing.JCheckBox SaidaCanal4;
    private javax.swing.JCheckBox SaidaCanal5;
    private javax.swing.JCheckBox SaidaCanal6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    protected javax.swing.JPanel jPanel4;
    private javax.swing.JMenu logMenuItem;
    private javax.swing.JButton pararSinalBt;
    protected javax.swing.JProgressBar tanque1Progress;
    protected javax.swing.JProgressBar tanque2Progress;
    // End of variables declaration//GEN-END:variables
}
