/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacontrole;

import java.awt.event.ActionListener;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jaime
 */
public class MainWindow extends javax.swing.JFrame {
    ImageIcon iconON = new ImageIcon(SistemaControle.class.getResource("/imagens/diagrama_on.png"));
    ImageIcon iconOFF = new ImageIcon(SistemaControle.class.getResource("/imagens/diagrama_off.png"));
    ImageIcon iconRV = new ImageIcon(SistemaControle.class.getResource("/imagens/diagrama_reverse.png"));
    DefaultTableModel model;
    TableColumnModel colunas;
    TableColumn col;
    List<TableColumn> colunasRemovidas;
    int tamColunas[] = new int[9];
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        
        initComponents();
        
        model.addColumn("SetPoint");
        model.addColumn("Tpico");
        model.addColumn("Tr 100%");
        model.addColumn("Tr 95%");
        model.addColumn("Tr 90%");
        model.addColumn("Ts 2%");
        model.addColumn("Ts 5%");
        model.addColumn("Ts 10%");
        model.addColumn("Mp% Mp");
        
        this.colunas = this.tabelaDetalhes.getColumnModel();
        for(int i=0; i<9; i++){
            this.colunas.getColumn(i).setMinWidth(0);
        }
        this.colunas.getColumn(3).setMaxWidth(0);
        this.colunas.getColumn(4).setMaxWidth(0);
        this.colunas.getColumn(5).setMaxWidth(0);
        this.colunas.getColumn(6).setMaxWidth(0);
        
        model.addRow(new Object[] { "0-10cm", "5s", "3s", "20s", "10s", "14s", "40s", "30s", "20% 2cm" });
    }
    
    //objeto model que vai ser usado para adicionar dinamicamente linhas a tabela
    public DefaultTableModel getTableModel(){
        return this.model;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ControleSelecao = new javax.swing.ButtonGroup();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PainelEntrada = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SaidaCanal0 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        SaidaCanal1 = new javax.swing.JCheckBox();
        SaidaCanal2 = new javax.swing.JCheckBox();
        SaidaCanal3 = new javax.swing.JCheckBox();
        SaidaCanal4 = new javax.swing.JCheckBox();
        SaidaCanal5 = new javax.swing.JCheckBox();
        SaidaCanal6 = new javax.swing.JCheckBox();
        BotaoLer = new javax.swing.JToggleButton();
        PainelSaida = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BotaoTipoDeFuncao = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pararSinalBt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tanque1Progress = new javax.swing.JProgressBar();
        tanque2Progress = new javax.swing.JProgressBar();
        LabelDiagrama = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDetalhes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tabelaSetPoint = new javax.swing.JCheckBox();
        tabelaMp = new javax.swing.JCheckBox();
        tabelaTs10 = new javax.swing.JCheckBox();
        tabelaTr100 = new javax.swing.JCheckBox();
        tabelaTr95 = new javax.swing.JCheckBox();
        tabelaTr90 = new javax.swing.JCheckBox();
        tabelaTpico = new javax.swing.JCheckBox();
        tabelaTs2 = new javax.swing.JCheckBox();
        tabelaTs5 = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        logMenuItem = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 714));
        setPreferredSize(new java.awt.Dimension(1370, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelEntrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PainelEntradaLayout = new javax.swing.GroupLayout(PainelEntrada);
        PainelEntrada.setLayout(PainelEntradaLayout);
        PainelEntradaLayout.setHorizontalGroup(
            PainelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        PainelEntradaLayout.setVerticalGroup(
            PainelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        getContentPane().add(PainelEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SaidaCanal0.setSelected(true);
        SaidaCanal0.setText("Canal 0");
        SaidaCanal0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal0ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Variáveis de Saída");

        SaidaCanal1.setText("Canal 1");
        SaidaCanal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal1ActionPerformed(evt);
            }
        });

        SaidaCanal2.setText("Canal 2");
        SaidaCanal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal2ActionPerformed(evt);
            }
        });

        SaidaCanal3.setText("Canal 3");
        SaidaCanal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal3ActionPerformed(evt);
            }
        });

        SaidaCanal4.setText("Canal 4");
        SaidaCanal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal4ActionPerformed(evt);
            }
        });

        SaidaCanal5.setText("Canal 5");
        SaidaCanal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal5ActionPerformed(evt);
            }
        });

        SaidaCanal6.setText("Canal 6");
        SaidaCanal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaCanal6ActionPerformed(evt);
            }
        });

        BotaoLer.setText("LER");
        BotaoLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SaidaCanal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaidaCanal5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SaidaCanal2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaidaCanal6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SaidaCanal3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoLer))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SaidaCanal0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaidaCanal4)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaidaCanal0)
                    .addComponent(SaidaCanal4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaidaCanal1)
                    .addComponent(SaidaCanal5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaidaCanal2)
                    .addComponent(SaidaCanal6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaidaCanal3)
                    .addComponent(BotaoLer))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 19, -1, -1));

        PainelSaida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PainelSaidaLayout = new javax.swing.GroupLayout(PainelSaida);
        PainelSaida.setLayout(PainelSaidaLayout);
        PainelSaidaLayout.setHorizontalGroup(
            PainelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        PainelSaidaLayout.setVerticalGroup(
            PainelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        getContentPane().add(PainelSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 388, -1, -1));

        jLabel7.setText("Níveis dos Tanques");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jLabel8.setText("Tensão das bombas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 359, -1, -1));

        BotaoTipoDeFuncao.setText("Tipo de Função");
        getContentPane().add(BotaoTipoDeFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 252, 176, 41));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pararSinalBt.setBackground(new java.awt.Color(255, 255, 255));
        pararSinalBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/stop.png"))); // NOI18N
        pararSinalBt.setText("Parar Sinal");
        pararSinalBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararSinalBtActionPerformed(evt);
            }
        });
        getContentPane().add(pararSinalBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 292, 120, 43));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tanque1Progress.setOrientation(1);
        tanque1Progress.setValue(50);
        tanque1Progress.setMaximumSize(new java.awt.Dimension(12, 10));
        tanque1Progress.setMinimumSize(new java.awt.Dimension(10, 10));
        tanque1Progress.setPreferredSize(new java.awt.Dimension(10, 10));
        tanque1Progress.setSize(new java.awt.Dimension(10, 10));

        tanque2Progress.setOrientation(1);
        tanque2Progress.setValue(50);

        LabelDiagrama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/diagrama_off.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/base.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("I");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelDiagrama, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tanque2Progress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanque1Progress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tanque1Progress, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(tanque2Progress, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelDiagrama))
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 388, -1, -1));

        tabelaDetalhes.setModel(model);
        jScrollPane2.setViewportView(tabelaDetalhes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 19, -1, -1));

        tabelaSetPoint.setSelected(true);
        tabelaSetPoint.setText("SetPoint");
        tabelaSetPoint.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabelaSetPointStateChanged(evt);
            }
        });

        tabelaMp.setSelected(true);
        tabelaMp.setText("Mp% Mp");
        tabelaMp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabelaMpStateChanged(evt);
            }
        });

        tabelaTs10.setSelected(true);
        tabelaTs10.setText("Ts 10%");
        tabelaTs10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabelaTs10StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaSetPoint)
            .addComponent(tabelaMp)
            .addComponent(tabelaTs10)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tabelaSetPoint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabelaMp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabelaTs10)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 440, -1, -1));

        tabelaTr100.setSelected(true);
        tabelaTr100.setText("Tr 100%");
        tabelaTr100.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabelaTr100StateChanged(evt);
            }
        });
        tabelaTr100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelaTr100ActionPerformed(evt);
            }
        });
        getContentPane().add(tabelaTr100, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 440, -1, -1));

        tabelaTr95.setText("Tr 95%");
        tabelaTr95.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabelaTr95StateChanged(evt);
            }
        });
        getContentPane().add(tabelaTr95, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 440, -1, -1));

        tabelaTr90.setText("Tr 90%");
        tabelaTr90.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabelaTr90StateChanged(evt);
            }
        });
        getContentPane().add(tabelaTr90, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 440, -1, -1));

        tabelaTpico.setSelected(true);
        tabelaTpico.setText("Tpico");
        tabelaTpico.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabelaTpicoStateChanged(evt);
            }
        });
        getContentPane().add(tabelaTpico, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 470, -1, -1));

        tabelaTs2.setText("Ts 2%");
        tabelaTs2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabelaTs2StateChanged(evt);
            }
        });
        getContentPane().add(tabelaTs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 470, -1, -1));

        tabelaTs5.setText("Ts 5%");
        tabelaTs5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabelaTs5StateChanged(evt);
            }
        });
        getContentPane().add(tabelaTs5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 470, -1, -1));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        logMenuItem.setText("Log");
        logMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logMenuItemActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Abrir log sistema");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        logMenuItem.add(jMenuItem3);

        jMenuBar1.add(logMenuItem);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void SaidaCanal0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal0ActionPerformed

    private void SaidaCanal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal1ActionPerformed

    private void SaidaCanal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal2ActionPerformed

    private void SaidaCanal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal3ActionPerformed

    private void SaidaCanal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal4ActionPerformed

    private void SaidaCanal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal5ActionPerformed

    private void SaidaCanal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaCanal6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaCanal6ActionPerformed

    private void BotaoLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLerActionPerformed

    private void logMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logMenuItemActionPerformed
        
    }//GEN-LAST:event_logMenuItemActionPerformed

    private void pararSinalBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararSinalBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pararSinalBtActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void tabelaTr100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelaTr100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaTr100ActionPerformed

    private void tabelaSetPointStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabelaSetPointStateChanged
        if(this.tabelaSetPoint.isSelected()){
            this.colunas.getColumn(0).setMaxWidth(200);
            this.colunas.getColumn(0).setPreferredWidth(90);
        }
        else{
            this.colunas.getColumn(0).setMaxWidth(0);
        }
    }//GEN-LAST:event_tabelaSetPointStateChanged

    private void tabelaTr100StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabelaTr100StateChanged
        if(this.tabelaTr100.isSelected()){
            this.colunas.getColumn(2).setMaxWidth(200);
            this.colunas.getColumn(2).setPreferredWidth(75);
        }
        else{
            this.colunas.getColumn(2).setMaxWidth(0);
        }
    }//GEN-LAST:event_tabelaTr100StateChanged

    private void tabelaTr95StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabelaTr95StateChanged
        if(this.tabelaTr95.isSelected()){
            this.colunas.getColumn(3).setMaxWidth(200);
            this.colunas.getColumn(3).setPreferredWidth(75);
        }
        else{
            this.colunas.getColumn(3).setMaxWidth(0);
        }
    }//GEN-LAST:event_tabelaTr95StateChanged

    private void tabelaTr90StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabelaTr90StateChanged
        if(this.tabelaTr90.isSelected()){
            this.colunas.getColumn(4).setMaxWidth(200);
            this.colunas.getColumn(4).setPreferredWidth(75);
        }
        else{
            this.colunas.getColumn(4).setMaxWidth(0);
        }
    }//GEN-LAST:event_tabelaTr90StateChanged

    private void tabelaTs2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabelaTs2StateChanged
        if(this.tabelaTs2.isSelected()){
            this.colunas.getColumn(5).setMaxWidth(200);
            this.colunas.getColumn(5).setPreferredWidth(75);
        }
        else{
            this.colunas.getColumn(5).setMaxWidth(0);
        }
    }//GEN-LAST:event_tabelaTs2StateChanged

    private void tabelaTs5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabelaTs5StateChanged
        if(this.tabelaTs5.isSelected()){
            this.colunas.getColumn(6).setMaxWidth(200);
            this.colunas.getColumn(6).setPreferredWidth(75);
        }
        else{
            this.colunas.getColumn(6).setMaxWidth(0);
        }
    }//GEN-LAST:event_tabelaTs5StateChanged

    private void tabelaTs10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabelaTs10StateChanged
        if(this.tabelaTs10.isSelected()){
            this.colunas.getColumn(7).setMaxWidth(200);
            this.colunas.getColumn(7).setPreferredWidth(75);
        }
        else{
            this.colunas.getColumn(7).setMaxWidth(0);
        }
    }//GEN-LAST:event_tabelaTs10StateChanged

    private void tabelaMpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabelaMpStateChanged
        if(this.tabelaMp.isSelected()){
            this.colunas.getColumn(8).setMaxWidth(200);
            this.colunas.getColumn(8).setPreferredWidth(85);
        }
        else{
            this.colunas.getColumn(8).setMaxWidth(0);
        }
    }//GEN-LAST:event_tabelaMpStateChanged

    private void tabelaTpicoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabelaTpicoStateChanged
        if(this.tabelaTpico.isSelected()){
            this.colunas.getColumn(1).setMaxWidth(200);
            this.colunas.getColumn(1).setPreferredWidth(75);
        }
        else{
            this.colunas.getColumn(1).setMaxWidth(0);
        }
    }//GEN-LAST:event_tabelaTpicoStateChanged
    public void addLerListener(ActionListener e){
        this.BotaoLer.addActionListener(e);
    }
    
    public void addLogWindowOpenListener(ActionListener e){
        this.logMenuItem.addActionListener(e);
    }
    
    public void addPararSinalListener(ActionListener e){
        this.pararSinalBt.addActionListener(e);
    }
    
    public boolean isCanal0(){
        return SaidaCanal0.isSelected();
    }
    public boolean isCanal1(){
        return SaidaCanal1.isSelected();
    }
    public boolean isCanal2(){
        return SaidaCanal2.isSelected();
    }
    public boolean isCanal3(){
        return SaidaCanal3.isSelected();
    }
    public boolean isCanal4(){
        return SaidaCanal4.isSelected();
    }
    public boolean isCanal5(){
        return SaidaCanal5.isSelected();
    }
    public boolean isCanal6(){
        return SaidaCanal6.isSelected();
    }
    
    public boolean[] isCanalSelected(){
        boolean[] canaisSelecionados = new boolean[7];
        if(isCanal0())
            canaisSelecionados[0] = true;
        else 
            canaisSelecionados[0] = false;
        
        if(isCanal1())
            canaisSelecionados[1] = true;
        else 
            canaisSelecionados[1] = false;
        
        if(isCanal2())
            canaisSelecionados[2] = true;
        else 
            canaisSelecionados[2] = false;
        
        if(isCanal3())
            canaisSelecionados[3] = true;
        else 
            canaisSelecionados[3] = false;
        
        if(isCanal4())
            canaisSelecionados[4] = true;
        else 
            canaisSelecionados[4] = false;
        
        if(isCanal5())
            canaisSelecionados[5] = true;
        else 
            canaisSelecionados[5] = false;
        
        if(isCanal6())
            canaisSelecionados[6] = true;
        else 
            canaisSelecionados[6] = false;
        
        
        return canaisSelecionados;
    }
    
    public void updateCanal0(double _valor){
        String valor;
        valor = String.valueOf(_valor);
    }
    public void updateCanal1(double _valor){
        String valor;
        valor = String.valueOf(_valor);
    }
    public void mostrarErro(String erro){
        JOptionPane.showMessageDialog(null, erro, "Erro!", JOptionPane.ERROR_MESSAGE);
    }
    public void mostrarAviso(String erro){
        JOptionPane.showMessageDialog(null, erro, "Aviso!", JOptionPane.WARNING_MESSAGE);
    }
    public void addTipoFuncaoListener(ActionListener listen){
        BotaoTipoDeFuncao.addActionListener(listen);
    }
    
    public void setTanque1Progress(double prog){
        int n = (int) prog;
        this.tanque1Progress.setValue(n);
    }
//    public MainWindow(ImageIcon diagrama){
//        LabelDiagrama.setIcon(diagrama);
//    }
    public void setTanque2Progress(double prog){
        int n = (int) prog;
        this.tanque2Progress.setValue(n);
    }
    
    public void AtualizarDiagrama(String tipo){
        if(tipo.equals("ON")){
            this.LabelDiagrama.setIcon(iconON);
            this.LabelDiagrama.repaint();
        }
        else if(tipo.equals("OFF")){
            this.LabelDiagrama.setIcon(iconOFF);
            this.LabelDiagrama.repaint();
        }
        else if(tipo.equals("RV")){
            this.LabelDiagrama.setIcon(iconRV);
            this.LabelDiagrama.repaint();
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoLer;
    private javax.swing.JButton BotaoTipoDeFuncao;
    private javax.swing.ButtonGroup ControleSelecao;
    protected javax.swing.JLabel LabelDiagrama;
    protected javax.swing.JPanel PainelEntrada;
    protected javax.swing.JPanel PainelSaida;
    private javax.swing.JCheckBox SaidaCanal0;
    private javax.swing.JCheckBox SaidaCanal1;
    private javax.swing.JCheckBox SaidaCanal2;
    private javax.swing.JCheckBox SaidaCanal3;
    private javax.swing.JCheckBox SaidaCanal4;
    private javax.swing.JCheckBox SaidaCanal5;
    private javax.swing.JCheckBox SaidaCanal6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    protected javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu logMenuItem;
    private javax.swing.JButton pararSinalBt;
    private javax.swing.JTable tabelaDetalhes;
    private javax.swing.JCheckBox tabelaMp;
    private javax.swing.JCheckBox tabelaSetPoint;
    private javax.swing.JCheckBox tabelaTpico;
    private javax.swing.JCheckBox tabelaTr100;
    private javax.swing.JCheckBox tabelaTr90;
    private javax.swing.JCheckBox tabelaTr95;
    private javax.swing.JCheckBox tabelaTs10;
    private javax.swing.JCheckBox tabelaTs2;
    private javax.swing.JCheckBox tabelaTs5;
    protected javax.swing.JProgressBar tanque1Progress;
    protected javax.swing.JProgressBar tanque2Progress;
    // End of variables declaration//GEN-END:variables
}
